// File generated by update_firebase_config.sh - DO NOT EDIT MANUALLY
// Generated for flavor: qa
// Generated at: Wed Aug  5 10:53:15 +0545 2026

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-1BoKk_jsPXlG4OFHOicL_jMAgeVToi8',
    appId: '1:775303366461:android:0d19919522cbfbdeb06754',
    messagingSenderId: '775303366461',
    projectId: 'vcare-admin',
    storageBucket: 'vcare-admin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEpE-6RXf3hU1HpkrK85OvkaJ4cVZDR_A',
    appId: '1:1042725938806:ios:abb0f29a22393afb7b6157',
    messagingSenderId: '1042725938806',
    projectId: 'starter-template-flutter-stag',
    storageBucket: 'starter-template-flutter-stag.firebasestorage.app',
    iosBundleId: 'com.vcare.admin.qa',
  );
}
