// File generated by update_firebase_config.sh - DO NOT EDIT MANUALLY
// Generated for flavor: dev
// Generated at: Mon May 18 03:04:36 +0545 2026

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLcFyihr4clriMXixTa-fDrZySWWOvJNw',
    appId: '1:680375809302:android:66b239b4ea633318008c37',
    messagingSenderId: '680375809302',
    projectId: 'starter-template-flutter-dev',
    storageBucket: 'starter-template-flutter-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxyXGODsmiwsBZZ3e6vcgueCjcjtl2lBE',
    appId: '1:680375809302:ios:62da2a66cf23d06f008c37',
    messagingSenderId: '680375809302',
    projectId: 'starter-template-flutter-dev',
    storageBucket: 'starter-template-flutter-dev.firebasestorage.app',
    iosBundleId: 'com.itheamc.fluttertemplate.dev',
  );
}
